# Generated by Django 5.2 on 2025-05-23 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_auditquestion_questionoption'),
        ('api', '0004_create_complaint_model'),
    ]

    operations = [
    ]
