# Generated by Django 5.2 on 2025-05-26 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_feedback_feedbackmethod_practice_feedbackattachment_and_more'),
        ('api', '0005_create_chatbot_models'),
        ('api', '0005_merge_20250523_1740'),
    ]

    operations = [
    ]
