# Generated by Django 5.2 on 2025-05-27 14:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_merge_20250526_1827'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbotmessage',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='chatbotquickaction',
            name='intent',
        ),
        migrations.RemoveField(
            model_name='chatbotresponse',
            name='intent',
        ),
        migrations.RemoveField(
            model_name='chatbotmessage',
            name='intent_detected',
        ),
        migrations.CreateModel(
            name='SimpleChatbotConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', max_length=20)),
                ('context', models.JSONField(default=dict, help_text='Conversation context and state')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'simple_chatbot_conversations',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='SimpleChatbotMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('user', 'User Message'), ('bot', 'Bot Response'), ('system', 'System Message')], max_length=20)),
                ('content', models.TextField()),
                ('intent_detected', models.CharField(blank=True, max_length=50, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict, help_text='Additional message metadata')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.simplechatbotconversation')),
            ],
            options={
                'db_table': 'simple_chatbot_messages',
                'ordering': ['timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='ChatbotConversation',
        ),
        migrations.DeleteModel(
            name='ChatbotQuickAction',
        ),
        migrations.DeleteModel(
            name='ChatbotResponse',
        ),
        migrations.DeleteModel(
            name='ChatbotIntent',
        ),
        migrations.DeleteModel(
            name='ChatbotMessage',
        ),
    ]
