name: Deploy Python App to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DEBUG: false
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
      HUGGINGFACEHUB_API_TOKEN: ${{ secrets.HUGGINGFACEHUB_API_TOKEN }}
      USE_HUGGINGFACE_API: ${{ secrets.USE_HUGGINGFACE_API }}
      LOCAL_MODELS_DIR: ${{ secrets.LOCAL_MODELS_DIR }}
      LOCAL_MODEL_DEVICE: ${{ secrets.LOCAL_MODEL_DEVICE }}
      LOCAL_MODEL_DTYPE: ${{ secrets.LOCAL_MODEL_DTYPE }}
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      USE_OPENROUTER_EMBEDDINGS: ${{ secrets.USE_OPENROUTER_EMBEDDINGS }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.2'

      - name: Install Python Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r ./medical_assistant_project/requirements.txt

      - name: Run Unit Tests
        working-directory: ./medical_assistant_project
        run: |
          source ../venv/bin/activate
          echo "Running tests..."  # Replace with: python manage.py test or pytest
          # Example: python ./medical_assistant_project/manage.py test

      - name: Collect Static Files (Django)
        if: success()
        working-directory: ./medical_assistant_project
        run: |
          source ../venv/bin/activate
          python manage.py collectstatic --noinput        

      - name: Login to Azure
        if: success()
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        if: success()
        uses: azure/webapps-deploy@v2
        with:
          app-name: mmc  # Replace with your actual Azure App Service name
          package: './medical_assistant_project'

      - name: Logout from Azure
        if: always()
        run: |
          az logout
          az account clear
