name: Deploy Python App to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./medical_assistant_project/requirements.txt

      - name: Run Unit Tests
        run: |
          echo "Running tests..."  # Replace with: python manage.py test or pytest
          # Example: python ./medical_assistant_project/manage.py test

      - name: Collect Static Files (Django)
        if: success()
        run: |
          python manage.py collectstatic --noinput
        working-directory: ./medical_assistant_project

      - name: Login to Azure
        if: success()
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        if: success()
        uses: azure/webapps-deploy@v2
        with:
          app-name: mmc  # Replace with your actual Azure App Service name
          package: './medical_assistant_project'

      - name: Logout from Azure
        if: always()
        run: |
          az logout
          az account clear
